'use strict';

var fs=require('fs-extra');
//const  path = require("path");

const excelToJson = require('convert-excel-to-json');
//const { browser } = require('protractor');

const result = excelToJson({

    source: fs.readFileSync('credential.xls'),
    header: {
        // Is the number of rows that will be skepped and wiil not be present at our result object
        rows:1
    }

});


//browser.ignoreSynchronization=true;
console.log('xcel output::',result)

console.log('url',result.logincred[0].B)

console.log('usercred',result.logincred[1].B)

console.log('passcred',result.logincred[2].B)

console.log('firstnameLead',result.Addleadparameters[0].A)

console.log('middlenameLead',result.Addleadparameters[0].B)

console.log('lastnameLead',result.Addleadparameters[0].C)

console.log('emailLead',result.Addleadparameters[0].D)

console.log('phnumber1',result.Addleadparameters[0].E)

console.log('phnumber2',result.Addleadparameters[0].F)

console.log('mobNumber',result.Addleadparameters[0].G)

console.log('genderName',result.Addleadparameters[0].H)

console.log('lyear',result.Addleadparameters[0].I)
console.log('lmonth',result.Addleadparameters[0].J)
console.log('lday',result.Addleadparameters[0].K)
console.log('occupation',result.Addleadparameters[0].L)

console.log('communicationlangauge',result.Addleadparameters[0].M)
console.log('conselor',result.Addleadparameters[0].N)

console.log('course',result.Addleadparameters[0].O)
console.log('academylocation',result.Addleadparameters[0].P)

console.log('courselangauge',result.Addleadparameters[0].Q) ,console.log('pincode',result.Addleadparameters[0].R)

console.log('addresstext1',result.Addleadparameters[0].S)

console.log('addresstext2',result.Addleadparameters[0].T)

console.log('Land',result.Addleadparameters[0].U)
console.log('exceedfirstname',result.Addleadparameters[1].A)
console.log('exceedmidlename',result.Addleadparameters[1].B)
console.log('exceedlastname',result.Addleadparameters[1].C)
console.log('Firstnamestaff',result.AddStaff[0].A)
console.log('Middlenamestaff',result.AddStaff[0].B)
console.log('Lastnamestaff',result.AddStaff[0].C)
console.log('Personelphone',result.AddStaff[0].D)
console.log('Workphone',result.AddStaff[0].E)
console.log('Email',result.AddStaff[0].F)
console.log('Role',result.AddStaff[0].G)
console.log('Designation',result.AddStaff[0].H)
console.log('Department',result.AddStaff[0].I)
console.log('TeachingStaff',result.AddStaff[0].J)
console.log('OfficeLocation',result.AddStaff[0].K)
console.log('Coursename',result.AddCourse[0].A)
console.log('Shortcode',result.AddCourse[0].B)
console.log('Courselocation',result.AddCourse[0].C)
console.log('LangaugeofInstruction',result.AddCourse[0].D)
console.log('PracticalRequirement',result.AddCourse[0].E)
console.log('MedicalHistoryRequirement',result.AddCourse[0].F)
console.log('ModesofInstruction',result.AddCourse[0].G)
console.log('Topic',result.AddCourse[0].H)
console.log('TheoryORpractical',result.AddCourse[0].I)
console.log('FeeType',result.AddCourse[0].J)
console.log('Feeamount',result.AddCourse[0].K)
console.log('Scalarshipreedemable',result.AddCourse[0].L)
console.log('UpfrontdiscountType',result.AddCourse[0].M)
console.log('UpfrontdiscountAmount',result.AddCourse[0].N)
console.log('PayablediscountType',result.AddCourse[0].O)
console.log('PayablediscountAmount',result.AddCourse[0].P)
console.log('BajajdiscountType',result.AddCourse[0].Q)
console.log('BajajDiscountamount',result.AddCourse[0].R)
console.log('BajajDownpayment',result.AddCourse[0].S)
console.log('BajajmaxInstallment',result.AddCourse[0].T)
console.log('BajajDocuments',result.AddCourse[0].U)
console.log('HDFCdiscountType',result.AddCourse[0].V)
console.log('HDFCDiscountamount',result.AddCourse[0].W)
console.log('HDFCDownpayment',result.AddCourse[0].X)
console.log('HDFCmaxInstallment',result.AddCourse[0].Y)
console.log('HDFCDocuments',result.AddCourse[0].Z)
console.log('K11discountType',result.AddCourse[0].AA)
console.log('K11Discountamount',result.AddCourse[0].AB)
console.log('K11Installments',result.AddCourse[0].AC)
console.log('K11Downpayment',result.AddCourse[0].AD)
console.log('K11maxInstallment',result.AddCourse[0].AE)
console.log('K11Documents',result.AddCourse[0].AF)
console.log('BatchLocation',result.AddCourse[0].AG)
console.log('PracticalLocation',result.AddCourse[0].AH)
console.log('BatchLangauge',result.AddCourse[0].AI)
console.log('Vertualcapacity',result.AddCourse[0].AJ)
console.log('Physicalcapacity',result.AddCourse[0].AK)
console.log('Startdate',result.AddCourse[0].AL)
console.log('Enddate',result.AddCourse[0].AM)
console.log('Starttime',result.AddCourse[0].AN)
console.log('Endtime',result.AddCourse[0].AO)
console.log('Frequency',result.AddCourse[0].AP)
console.log('Student',result.NewTicket[0].A)
console.log('Course',result.NewTicket[0].B)
console.log('Subject',result.NewTicket[0].C)
console.log('Department',result.NewTicket[0].D)
console.log('Category',result.NewTicket[0].E)
console.log('Subcategory',result.NewTicket[0].F)
console.log('Tags',result.NewTicket[0].G)
console.log('Nextdate',result.NewTicket[0].H)
console.log('Starttime',result.NewTicket[0].I)
console.log('Endtime',result.NewTicket[0].J)
console.log('Status',result.NewTicket[0].K)
console.log('Priority',result.NewTicket[0].L)
console.log('Changenote',result.NewTicket[0].M)
console.log('upadatestaffname',result.AddStaff[2].A)
console.log('updatestafflastname',result.AddStaff[2].B)
console.log('updatestaffworkphone',result.AddStaff[2].C)
console.log('nametoreplace',result.AddStaff[2].D)
console.log('updatefirstname',result.AddStaff[2].E)
console.log('nametoreplacefirstname',result.AddStaff[2].F)
console.log('updatemiddlename',result.AddStaff[2].G)
console.log('nametoreplacemidlename',result.AddStaff[2].H)
console.log('updatepersonalphone',result.AddStaff[2].I)
console.log('numbertoreplacepersonel',result.AddStaff[2].J)
console.log('updateworkphone',result.AddStaff[2].K)
console.log('numbertoreplaceworkphone',result.AddStaff[2].L)
console.log('updateemail',result.AddStaff[2].M)
console.log('emailtoreplace',result.AddStaff[2].N)
console.log('updaterole',result.AddStaff[2].O)
console.log('roletobereplace',result.AddStaff[2].P)
console.log('updatedesignation',result.AddStaff[2].Q)
console.log('designationtoreplace',result.AddStaff[2].R)
console.log('updatedepartment',result.AddStaff[2].S)
console.log('departmenttoreplace',result.AddStaff[2].T)
console.log('updateteachingStaff',result.AddStaff[2].U)
console.log('teachingstafftoreplace',result.AddStaff[2].V)
console.log('updateofficelocation',result.AddStaff[2].W)
console.log('officelocationtoreplace',result.AddStaff[2].X)
console.log('leadtoupdate',result.Addleadparameters[3].A)
console.log('updatefirstnamelead',result.Addleadparameters[3].B)
console.log('replacefirstnamelead',result.Addleadparameters[3].C)
console.log('updatemidlenamelead',result.Addleadparameters[3].D)
console.log('replacemidlenamelead',result.Addleadparameters[3].E)
console.log('updatelastnamelead',result.Addleadparameters[3].F)
console.log('replacelasnamelead',result.Addleadparameters[3].G)
console.log('updateemaillead',result.Addleadparameters[3].H)
console.log('replaceemaillead',result.Addleadparameters[3].I)
console.log('updatephone',result.Addleadparameters[3].J)
console.log('replacephone',result.Addleadparameters[3].K)
console.log('updatealternatephone',result.Addleadparameters[3].L)
console.log('replacealternatephone',result.Addleadparameters[3].M)
console.log('updatewhatsapp',result.Addleadparameters[3].N)
console.log('replacewhatsapp',result.Addleadparameters[3].O)
console.log('updategender',result.Addleadparameters[3].P)
console.log('replacegender',result.Addleadparameters[3].Q)
console.log('updateDOB',result.Addleadparameters[3].R)
console.log('replaceDOB',result.Addleadparameters[3].S)
console.log('updateoccupation',result.Addleadparameters[3].T)
console.log('replaceoccupation',result.Addleadparameters[3].U)
console.log('updatecommlangauge',result.Addleadparameters[3].V)
console.log('replacecommlangauge',result.Addleadparameters[3].W)
console.log('updateconselor',result.Addleadparameters[3].X)
console.log('replaceconselor',result.Addleadparameters[3].Y)
console.log('updatecourse',result.Addleadparameters[3].Z)
console.log('replacecourse',result.Addleadparameters[3].AA)
console.log('updateacademy',result.Addleadparameters[3].AB)
console.log('replaceacademy',result.Addleadparameters[3].AC)
console.log('updatecourselangauge',result.Addleadparameters[3].AD)
console.log('replacecourselang',result.Addleadparameters[3].AE)
console.log('updatepostalcode',result.Addleadparameters[3].AF)
console.log('replacepostalcode',result.Addleadparameters[3].AG)
console.log('updateaddress1',result.Addleadparameters[3].AH)
console.log('replaceaddress1',result.Addleadparameters[3].AI)
console.log('updateaddress2',result.Addleadparameters[3].AJ)
console.log('replaceaddress2',result.Addleadparameters[3].AK)
console.log('updatelandmark',result.Addleadparameters[3].AL)
console.log('replacelandmark',result.Addleadparameters[3].AM)
console.log('searchstudenttoupdateticket',result.NewTicket[2].A)
console.log('searchcoursename',result.AddCourse[2].A)
console.log('updatecourselocation',result.AddCourse[2].B)
console.log('replacecourselocation',result.AddCourse[2].C)
console.log('updatelangaugeinstruction',result.AddCourse[2].D)
console.log('replacelangaugeinstruction',result.AddCourse[2].E)
console.log('updatepracticalrequirement',result.AddCourse[2].F)
console.log('replacepracticalrequirement',result.AddCourse[2].G)
console.log('updatemedicalrequirement',result.AddCourse[2].H)
console.log('replacemedicalrequirement',result.AddCourse[2].I)
console.log('updatemodeofinstruction',result.AddCourse[2].J)
console.log('replacemodeofinstruction',result.AddCourse[2].K)
console.log('updatetopic',result.AddCourse[2].L)
console.log('replacetopic',result.AddCourse[2].M)
console.log('Updateradiobutton',result.AddCourse[2].N)
console.log('replaceradiobutton',result.AddCourse[2].O)
console.log('updatefeetype',result.AddCourse[2].P)
console.log('replacefeetype',result.AddCourse[2].Q)
console.log('updatefeeamount',result.AddCourse[2].R)
console.log('replacefeeamount',result.AddCourse[2].S)
console.log('updatecreditredeemable',result.AddCourse[2].T)
console.log('replacecreditredeemable',result.AddCourse[2].U)
console.log('updatebatchlocation',result.AddCourse[2].V)
console.log('replacebatchlocation',result.AddCourse[2].W)
console.log('updatepracticallocation',result.AddCourse[2].X)
console.log('replacepracticallocation',result.AddCourse[2].Y)
console.log('updatebatchlaungauge',result.AddCourse[2].Z)
console.log('replacebatchlaungauge',result.AddCourse[2].AA)
console.log('updatevirtualcapacity',result.AddCourse[2].AB)
console.log('replacevirtualcapacity',result.AddCourse[2].AC)
console.log('updatephysicalcapacity',result.AddCourse[2].AD)
console.log('replacephysicalcapacity',result.AddCourse[2].AE)
console.log('updatebatchstartdate',result.AddCourse[2].AF)
console.log('replacedate',result.AddCourse[2].AG)
console.log('updatebatchenddate',result.AddCourse[2].AH)
console.log('replacebatchenddate',result.AddCourse[2].AI)
console.log('updatebatchtime',result.AddCourse[2].AJ)
console.log('updatestarttime',result.AddCourse[2].AK)
console.log('replacestarttime',result.AddCourse[2].AL)
console.log('updateendtime',result.AddCourse[2].AM)
console.log('replaceendtime',result.AddCourse[2].AN)
console.log('updatefrequency',result.AddCourse[2].AO)
console.log('replacefrequency',result.AddCourse[2].AP)
console.log('updateweek1',result.AddCourse[2].AQ)
console.log('Week',result.AddCourse[0].AQ)
console.log('updateadminfirstname',result.AdminProfile[0].A)
console.log('replacefirstname',result.AdminProfile[0].B)
console.log('updateadminmiddlename',result.AdminProfile[0].C)
console.log('replaceadminmiddlename',result.AdminProfile[0].D)
console.log('updateadminlastname',result.AdminProfile[0].E)
console.log('replaceadminlastname',result.AdminProfile[0].F)
console.log('admingender',result.AdminProfile[0].G)
console.log('adminDOB',result.AdminProfile[0].H)
console.log('updateadminphone',result.AdminProfile[0].I)
console.log('replaceadminphone',result.AdminProfile[0].J)
console.log('Mandatoryleadfirstname',result.Addleadparameters[5].A)
console.log('Mandatoryleademail',result.Addleadparameters[5].B)
console.log('Mandatoryleadphone',result.Addleadparameters[5].C)
console.log('Mandatoryleadgender',result.Addleadparameters[5].D)
console.log('MandatoryleadDOByear',result.Addleadparameters[5].E)
console.log('MandatoryleadDOBmonth',result.Addleadparameters[5].F)
console.log('MandatoryleadDOByearday',result.Addleadparameters[5].G)
console.log('Mandatoryleadconselor',result.Addleadparameters[5].H)
console.log('MandatoryleadCourse',result.Addleadparameters[5].I)
console.log('MandatoryleadAcademy',result.Addleadparameters[5].J)
console.log('MandatoryleadPincode',result.Addleadparameters[5].K)
console.log('Meandatoryleadflatnumber',result.Addleadparameters[5].L)
console.log('Mendatoryleadstreetarea',result.Addleadparameters[5].M)
console.log('firstnameLeadnumbers',result.Addleadparameters[7].A)
console.log('firstnameLeadsymbols',result.Addleadparameters[7].B)
console.log('leademailfieldwithnumbers',result.Addleadparameters[7].C)
console.log('leademailfieldwithsymbols',result.Addleadparameters[7].D)
console.log('leadphonefieldwithletters',result.Addleadparameters[7].E)
console.log('leadphonefieldwithinvalidnum',result.Addleadparameters[7].F)
console.log('leadphonefieldwithvalidnum',result.Addleadparameters[7].G)
console.log('leadphonefieldwithmorethan10digits',result.Addleadparameters[7].H)
console.log('leadphonefieldwithlessthan10digits',result.Addleadparameters[7].I)
console.log('leadphonefieldwithsymbols',result.Addleadparameters[7].J)
console.log('leadpostalcodefieldwithletters',result.Addleadparameters[7].K)
console.log('leadpostalcodefieldwithsymbol',result.Addleadparameters[7].L)
console.log('leadpostalcodefieldlessthan6digit',result.Addleadparameters[7].M)
console.log('leadpostalcodefieldgreaterthan6digit',result.Addleadparameters[7].N)
console.log('leadpostalcodefieldwithvalidpin',result.Addleadparameters[7].O)
console.log('leadflatnumberfieldwithmorethan100letters',result.Addleadparameters[7].P)
console.log('leadareafieldwithgreater100letters',result.Addleadparameters[7].Q)
console.log('leadmiddlenamewithnumbers',result.Addleadparameters[7].R)
console.log('leadmiddlenamewithsymbols',result.Addleadparameters[7].S)
console.log('leadmiddlenamewithvalidname',result.Addleadparameters[7].T)
console.log('leadmiddlenamewithmorethan30characters',result.Addleadparameters[7].U)
console.log('leadlastnamewithnumbers',result.Addleadparameters[7].V)
console.log('leadlastnamewithsymbols',result.Addleadparameters[7].W)
console.log('leadlastnamewithvalidname',result.Addleadparameters[7].X)
console.log('leadlastnamewithgreaterthan30characters',result.Addleadparameters[7].Y)
console.log('leadalternatephonewithletters',result.Addleadparameters[7].Z)
console.log('leadalternatephonewithinvalidnumber',result.Addleadparameters[7].AA)
console.log('leadalternatephonewithvalidnumber',result.Addleadparameters[7].AB)
console.log('leadalternatephonewithgreaterthan10digits',result.Addleadparameters[7].AC)
console.log('leadalternatephonewithlessthan10',result.Addleadparameters[7].AD)
console.log('leadalternatephonewithsymbols',result.Addleadparameters[7].AE)
console.log('leadwhatsappwithletters',result.Addleadparameters[7].AF)
console.log('leadwhatsappwithinvalidnumber',result.Addleadparameters[7].AG)
console.log('leadwhatsappwithvalidnumber',result.Addleadparameters[7].AH)
console.log('leadwhatsappwithgreaterthan10numbers',result.Addleadparameters[7].AI)
console.log('leadwhatsappwithlessthan10',result.Addleadparameters[7].AJ)
console.log('leadwhatsappwithsymbols',result.Addleadparameters[7].AK)
console.log('leadoccupationwithmaxvalidation',result.Addleadparameters[7].AL)
console.log('leadlandmarkfieldwithmaxvalidation',result.Addleadparameters[7].AM)
console.log('prefferedstarttime',result.Addleadparameters[0].V)
console.log('prefferedendtime',result.Addleadparameters[0].W)
console.log('leadprefferedstarttimewithwrongtime',result.Addleadparameters[7].AN)
console.log('leadprefferedcallingendtimewithwrongtime',result.Addleadparameters[7].AO)
console.log('Mandatorystafffirstname',result.AddStaff[4].A)
console.log('Mandatorystaffpersonalphone',result.AddStaff[4].B)
console.log('Mandatorystaffemail',result.AddStaff[4].C)
console.log('Mandatorystaffrole',result.AddStaff[4].D)
console.log('Mandatorystaffdesignation',result.AddStaff[4].E)
console.log('Mandatorystaffdepartment',result.AddStaff[4].F)
console.log('Mandatorystaffteaching',result.AddStaff[4].G)
console.log('Mandatorystaffofficelocation',result.AddStaff[4].H)
console.log('stafffirstnamewithnumbers',result.AddStaff[4].I)
console.log('stafffirstnamewithsymbols',result.AddStaff[4].J)
console.log('stafffirstnamewithmaxvalidation',result.AddStaff[4].K)
console.log('staffmiddlenamewithnumbers',result.AddStaff[4].L)
console.log('staffmiddlenamewithsymbols',result.AddStaff[4].M)
console.log('staffmiddlenamewithvalidname',result.AddStaff[4].N)
console.log('Staffmiddlenamewithmaxvalidation',result.AddStaff[4].O)
console.log('stafflastnamewithnumbers',result.AddStaff[4].P)
console.log('stafflastnamewithsymbols',result.AddStaff[4].Q)
console.log('stafflastnamewithvalidname',result.AddStaff[4].R)
console.log('stafflastnamewithmaxvalidation',result.AddStaff[4].S)
console.log('staffphonewithletters',result.AddStaff[4].T)
console.log('staffphonewithinvalidnumber',result.AddStaff[4].U)
console.log('staffphonewithvalidnumber',result.AddStaff[4].V)
console.log('staffphonewithgreaterthan10',result.AddStaff[4].W)
console.log('staffphonewithlessthan10',result.AddStaff[4].X)
console.log('staffphonewithsymbols',result.AddStaff[4].Y)
console.log('staffworkphonewithletters',result.AddStaff[4].Z)
console.log('staffworkphonewithinvalidnumber',result.AddStaff[4].AA)
console.log('staffworkphonewithvalidnumber',result.AddStaff[4].AB)
console.log('staffworkwithgreaterthan10',result.AddStaff[4].AC)
console.log('staffworkphonewithlessthan10',result.AddStaff[4].AD)
console.log('staffworkphonewithsymbols',result.AddStaff[4].AE)
console.log('staffemailwithnumbers',result.AddStaff[4].AF)
console.log('staffemailwithsymbols',result.AddStaff[4].AG)
console.log('staffemailwithvalidemail',result.AddStaff[4].AH)
console.log('courseoverviewwithmandatorycoursename',result.AddCourse[4].A)
console.log('courseoverviewwithmandatorycourseshrtcode',result.AddCourse[4].B)
console.log('coursenamefieldwithgreaterthan100characters',result.AddCourse[4].C)
console.log('courseshortcodewithgreaterthan100characters',result.AddCourse[4].D)
console.log('coursenamewithvaliddata',result.AddCourse[4].E)
console.log('courseshortcodewithvaliddata',result.AddCourse[4].F)
console.log('Verifycourse',result.AddCourse[4].G)
console.log('coursebasicbycourselocation',result.AddCourse[4].H)
console.log('coursebasicbylangaugeofinsrtuction',result.AddCourse[4].I)
console.log('coursebasicbypracticalrequirement',result.AddCourse[4].J)
console.log('coursebasicbymedicalrequirement',result.AddCourse[4].K)
console.log('coursebasicbymodesofinstruction',result.AddCourse[4].L)
console.log('searchedcoursetobeclicked',result.AddCourse[4].M)
console.log('coursefeeamount',result.AddCourse[4].N)
console.log('coursepaymentredeemablecredit',result.AddCourse[4].O)
console.log('coursepaymentredeemablemasking',result.AddCourse[4].P)
console.log('coursepaymentflatdiscountamountverificationforUpfront',result.AddCourse[4].Q)
console.log('coursepaymentdiscontamountforflat',result.AddCourse[4].R)
console.log('coursepaymentpercentagediscountamountverificationforUpfront',result.AddCourse[4].S)
console.log('coursepaymentdiscontamountforpercentage',result.AddCourse[4].T)
console.log('courseschedulevirtualcapacitybyletters',result.AddCourse[4].U)
console.log('courseschedulevirtualcapacitybysymbols',result.AddCourse[4].V)
console.log('courseschedulephysicalcapacitybyletters',result.AddCourse[4].W)
console.log('courseschedulephysicalcapacitybysymbols',result.AddCourse[4].X)
console.log('courseschedulebatchstarttime',result.AddCourse[4].Y)
console.log('courseschedulebatchendtime',result.AddCourse[4].Z)
console.log('coursepaymentbajajdiscountamountforflat',result.AddCourse[4].AA)
console.log('coursepaymentbajajdiscountamountforpercentage',result.AddCourse[4].AB)
console.log('coursepaymentbajajdownpaymentbypassingmaxvalue',result.AddCourse[4].AC)
console.log('coursepaymentbajajdownpaymentformaskeddata',result.AddCourse[4].AD)
console.log('coursepaymentbajajmaxinstallementswithletters',result.AddCourse[4].AE)
console.log('coursepaymentbajajmaxinstallementswithsymbols',result.AddCourse[4].AF)
console.log('coursepaymentbajajmaxinstallementswithmaxvalue',result.AddCourse[4].AG)
console.log('coursepaymenthdfcdiscountamountforflatdiscount',result.AddCourse[4].AH)
console.log('coursepaymenthdfcdiscountamountforpercentagediscount',result.AddCourse[4].AI)
console.log('coursepaymenthdfcdownpaymentformaxvalue',result.AddCourse[4].AJ)
console.log('coursepaymenthdfcdownpaymentformasked',result.AddCourse[4].AK)
console.log('coursepaymentHDFCmaxinstallmentwithletters',result.AddCourse[4].AL)
console.log('coursepaymentHDFCmaxinstallmentwithsymbols',result.AddCourse[4].AM)
console.log('coursepaymentHDFCmaxinstallmentwithmaxvalue',result.AddCourse[4].AN)
console.log('coursepaymentK11discountamountforflat',result.AddCourse[4].AO)
console.log('coursepaymentK11discountamountforpercentage',result.AddCourse[4].AP)
console.log('coursepaymentK11downpaymentformaxvalue',result.AddCourse[4].AQ)
console.log('coursepaymentK11downpaymentformaskedvalue',result.AddCourse[4].AR)
console.log('coursepaymentK11maxintallmentswithletters',result.AddCourse[4].AS)
console.log('coursepaymentK11maxintallmentswithsymbols',result.AddCourse[4].AT)
console.log('coursepaymentK11maxintallmentswithmaxvalue',result.AddCourse[4].AU)
console.log('coursepaymentpayablediscountamountforflat',result.AddCourse[4].AV)
console.log('coursepaymentpayablediscountamountforpercentage',result.AddCourse[4].AW)
console.log('organizationcode',result.logincred[3].B)
console.log('updateweek2',result.AddCourse[2].AR)
console.log('updateweek3',result.AddCourse[2].AS)
console.log('updateweek4',result.AddCourse[2].AT)
console.log('usernamewithletters',result.logincred[4].B)
console.log('usernamewithsymbols',result.logincred[5].B)
console.log('usernamewithnumbers',result.logincred[6].B)
console.log('usernamewithinvalidemail',result.logincred[7].B)
console.log('usernamewithvalidemail',result.logincred[8].B)
console.log('wrongusername',result.logincred[9].B)
console.log('wrongpassword',result.logincred[10].B)
console.log('forgotpasswordusernamewithletters',result.logincred[11].B)
console.log('forgotpasswordusernamewithsymbols',result.logincred[12].B)
console.log('forgotpasswordusernamewithnumbers',result.logincred[13].B)
console.log('forgotpasswordusernamewithvalidemail',result.logincred[14].B)
console.log('forgotpasswordusernamewithinvalidemail',result.logincred[15].B)
console.log('course1',result.AddCourse[6].A)
console.log('courseshortcode1',result.AddCourse[6].B)
console.log('course2',result.AddCourse[6].C)
console.log('courseshortcode2',result.AddCourse[6].D)
console.log('course3',result.AddCourse[6].E)
console.log('courseshortcode3',result.AddCourse[6].F)
console.log('course4',result.AddCourse[6].G)
console.log('courseshortcode4',result.AddCourse[6].H)
console.log('course5',result.AddCourse[6].I)
console.log('courseshortcode5',result.AddCourse[6].J)
console.log('course6',result.AddCourse[6].K)
console.log('courseshortcode6',result.AddCourse[6].L)


var dataRequired = function(){
    //browser.ignoreSynchronization=true;

    
    this.testConfig={

        
        url:result.logincred[0].B,
        usercred:result.logincred[1].B,
        passcred:result.logincred[2].B,
        firstnameLead:result.Addleadparameters[0].A,
        middlenameLead:result.Addleadparameters[0].B,
        lastnameLead:result.Addleadparameters[0].C,
        emailLead:result.Addleadparameters[0].D,
        phnumber1:result.Addleadparameters[0].E,
        phnumber2:result.Addleadparameters[0].F,
        mobNumber:result.Addleadparameters[0].G,
        genderName:result.Addleadparameters[0].H,
        lyear:result.Addleadparameters[0].I,
        lmonth:result.Addleadparameters[0].J,
        lday:result.Addleadparameters[0].K,
        occupation:result.Addleadparameters[0].L,
        communicationlangauge:result.Addleadparameters[0].M,
        conselor:result.Addleadparameters[0].N,       
        course:result.Addleadparameters[0].O,
        academylocation:result.Addleadparameters[0].P,
        courselangauge:result.Addleadparameters[0].Q,
        pincode:result.Addleadparameters[0].R,
        addresstext1:result.Addleadparameters[0].S,
        addresstext2:result.Addleadparameters[0].T,
        Land:result.Addleadparameters[0].U,
        exceedfirstname:result.Addleadparameters[1].A,
        exceedmidlename:result.Addleadparameters[1].B,
        exceedlastname:result.Addleadparameters[1].C,
        Firstnamestaff:result.AddStaff[0].A,
        Middlenamestaff:result.AddStaff[0].B,
        Lastnamestaff:result.AddStaff[0].C,
        Personelphone:result.AddStaff[0].D,
        Workphone:result.AddStaff[0].E,
        Email:result.AddStaff[0].F,
        Role:result.AddStaff[0].G,
        Designation:result.AddStaff[0].H,
        Department:result.AddStaff[0].I,
        TeachingStaff:result.AddStaff[0].J,
        OfficeLocation:result.AddStaff[0].K,
        Coursename:result.AddCourse[0].A,
        Shortcode:result.AddCourse[0].B,
        Courselocation:result.AddCourse[0].C,
        LangaugeofInstruction:result.AddCourse[0].D,
        PracticalRequirement:result.AddCourse[0].E,
        MedicalHistoryRequirement:result.AddCourse[0].F,
        ModesofInstruction:result.AddCourse[0].G,
        Topic:result.AddCourse[0].H,
        TheoryORpractical:result.AddCourse[0].I,
        FeeType:result.AddCourse[0].J,
        Feeamount:result.AddCourse[0].K,        
        Scalarshipreedemable:result.AddCourse[0].L,
        UpfrontdiscountType:result.AddCourse[0].M,
        UpfrontdiscountAmount:result.AddCourse[0].N,
        PayablediscountType:result.AddCourse[0].O,
        PayablediscountAmount:result.AddCourse[0].P,
        BajajdiscountType:result.AddCourse[0].Q,
        BajajDiscountamount:result.AddCourse[0].R,
        BajajDownpayment:result.AddCourse[0].S,
        BajajmaxInstallment:result.AddCourse[0].T,
        BajajDocuments:result.AddCourse[0].U,
        HDFCdiscountType:result.AddCourse[0].V,
        HDFCDiscountamount:result.AddCourse[0].W,
        HDFCDownpayment:result.AddCourse[0].X,
        HDFCmaxInstallment:result.AddCourse[0].Y,
        HDFCDocuments:result.AddCourse[0].Z,
        K11discountType:result.AddCourse[0].AA,
        K11Discountamount:result.AddCourse[0].AB,
        K11Installments:result.AddCourse[0].AC,
        K11Downpayment:result.AddCourse[0].AD,
        K11maxInstallment:result.AddCourse[0].AE,
        K11Documents:result.AddCourse[0].AF,
        BatchLocation:result.AddCourse[0].AG,
        PracticalLocation:result.AddCourse[0].AH,
        BatchLangauge:result.AddCourse[0].AI,
        Vertualcapacity:result.AddCourse[0].AJ,
        Physicalcapacity:result.AddCourse[0].AK,
        Startdate:result.AddCourse[0].AL,
        Enddate:result.AddCourse[0].AM,
        Starttime:result.AddCourse[0].AN,
        Endtime:result.AddCourse[0].AO,
        Frequency:result.AddCourse[0].AP,
        Student:result.NewTicket[0].A,
        Course:result.NewTicket[0].B,
        Subject:result.NewTicket[0].C,
        Department:result.NewTicket[0].D,
        Category:result.NewTicket[0].E,
        Subcategory:result.NewTicket[0].F,
        Tags:result.NewTicket[0].G,
        Nextdate:result.NewTicket[0].H,
        Starttime:result.NewTicket[0].I,
        Endtime:result.NewTicket[0].J,
        Status:result.NewTicket[0].K,
        Priority:result.NewTicket[0].L,
        Changenote:result.NewTicket[0].M,
        upadatestaffname:result.AddStaff[2].A,
        updatestafflastname:result.AddStaff[2].B,
        updatestaffworkphone:result.AddStaff[2].C,
        nametoreplace:result.AddStaff[2].D,
        updatefirstname:result.AddStaff[2].E,
        nametoreplacefirstname:result.AddStaff[2].F,
        updatemiddlename:result.AddStaff[2].G,
        nametoreplacemidlename:result.AddStaff[2].H,
        updatepersonalphone:result.AddStaff[2].I,
        numbertoreplacepersonel:result.AddStaff[2].J,
        updateworkphone:result.AddStaff[2].K,
        numbertoreplaceworkphone:result.AddStaff[2].L,
        updateemail:result.AddStaff[2].M,
        emailtoreplace:result.AddStaff[2].N,
        updaterole:result.AddStaff[2].O,
        roletobereplace:result.AddStaff[2].P,
        updatedesignation:result.AddStaff[2].Q,
        designationtoreplace:result.AddStaff[2].R,
        updatedepartment:result.AddStaff[2].S,
        departmenttoreplace:result.AddStaff[2].T,
        updateteachingStaff:result.AddStaff[2].U,
        teachingstafftoreplace:result.AddStaff[2].V,
        updateofficelocation:result.AddStaff[2].W,
        officelocationtoreplace:result.AddStaff[2].X,
        leadtoupdate:result.Addleadparameters[3].A,
        updatefirstnamelead:result.Addleadparameters[3].B,
        replacefirstnamelead:result.Addleadparameters[3].C,
        updatemidlenamelead:result.Addleadparameters[3].D,
        replacemidlenamelead:result.Addleadparameters[3].E,
        updatelastnamelead:result.Addleadparameters[3].F,
        replacelasnamelead:result.Addleadparameters[3].G,
        updateemaillead:result.Addleadparameters[3].H,
        replaceemaillead:result.Addleadparameters[3].I,
        updatephone:result.Addleadparameters[3].J,
        replacephone:result.Addleadparameters[3].K,
        updatealternatephone:result.Addleadparameters[3].L,
        replacealternatephone:result.Addleadparameters[3].M,
        updatewhatsapp:result.Addleadparameters[3].N,
        replacewhatsapp:result.Addleadparameters[3].O,
        updategender:result.Addleadparameters[3].P,
        replacegender:result.Addleadparameters[3].Q,
        updateDOB:result.Addleadparameters[3].R,
        replaceDOB:result.Addleadparameters[3].S,
        updateoccupation:result.Addleadparameters[3].T,
        replaceoccupation:result.Addleadparameters[3].U,
        updatecommlangauge:result.Addleadparameters[3].V,
        replacecommlangauge:result.Addleadparameters[3].W,
        updateconselor:result.Addleadparameters[3].X,
        replaceconselor:result.Addleadparameters[3].Y,
        updatecourse:result.Addleadparameters[3].Z,
        replacecourse:result.Addleadparameters[3].AA,
        updateacademy:result.Addleadparameters[3].AB,
        replaceacademy:result.Addleadparameters[3].AC,
        updatecourselangauge:result.Addleadparameters[3].AD,
        replacecourselang:result.Addleadparameters[3].AE,
        updatepostalcode:result.Addleadparameters[3].AF,
        replacepostalcode:result.Addleadparameters[3].AG,
        updateaddress1:result.Addleadparameters[3].AH,
        replaceaddress1:result.Addleadparameters[3].AI,
        updateaddress2:result.Addleadparameters[3].AJ,
        replaceaddress2:result.Addleadparameters[3].AK,
        updatelandmark:result.Addleadparameters[3].AL,
        replacelandmark:result.Addleadparameters[3].AM,
        searchstudenttoupdateticket:result.NewTicket[2].A,
        searchcoursename:result.AddCourse[2].A,
        updatecourselocation:result.AddCourse[2].B,
        replacecourselocation:result.AddCourse[2].C,
        updatelangaugeinstruction:result.AddCourse[2].D,
        replacelangaugeinstruction:result.AddCourse[2].E,
        updatepracticalrequirement:result.AddCourse[2].F,
        replacepracticalrequirement:result.AddCourse[2].G,
        updatemedicalrequirement:result.AddCourse[2].H,
        replacemedicalrequirement:result.AddCourse[2].I,
        updatemodeofinstruction:result.AddCourse[2].J,
        replacemodeofinstruction:result.AddCourse[2].K,
        updatetopic:result.AddCourse[2].L,
        replacetopic:result.AddCourse[2].M,
        Updateradiobutton:result.AddCourse[2].N,
        replaceradiobutton:result.AddCourse[2].O,
        updatefeetype:result.AddCourse[2].P,
        replacefeetype:result.AddCourse[2].Q,
        updatefeeamount:result.AddCourse[2].R,
        replacefeeamount:result.AddCourse[2].S,
        updatecreditredeemable:result.AddCourse[2].T,
        replacecreditredeemable:result.AddCourse[2].U,
        updatebatchlocation:result.AddCourse[2].V,
        replacebatchlocation:result.AddCourse[2].W,
        updatepracticallocation:result.AddCourse[2].X,
        replacepracticallocation:result.AddCourse[2].Y,
        updatebatchlaungauge:result.AddCourse[2].Z,
        replacebatchlaungauge:result.AddCourse[2].AA,
        updatevirtualcapacity:result.AddCourse[2].AB,
        replacevirtualcapacity:result.AddCourse[2].AC,
        updatephysicalcapacity:result.AddCourse[2].AD,
        replacephysicalcapacity:result.AddCourse[2].AE,
        updatebatchstartdate:result.AddCourse[2].AF,
        replacedate:result.AddCourse[2].AG,
        updatebatchenddate:result.AddCourse[2].AH,
        replacebatchenddate:result.AddCourse[2].AI,
        updatebatchtime:result.AddCourse[2].AJ,
        updatestarttime:result.AddCourse[2].AK,
        replacestarttime:result.AddCourse[2].AL,
        updateendtime:result.AddCourse[2].AM,
        replaceendtime:result.AddCourse[2].AN,
        updatefrequency:result.AddCourse[2].AO,
        replacefrequency:result.AddCourse[2].AP,
        updateweek1:result.AddCourse[2].AQ,
        Week :result.AddCourse[0].AQ,
        updateadminfirstname:result.AdminProfile[0].A,
        replacefirstname:result.AdminProfile[0].B,
        updateadminmiddlename:result.AdminProfile[0].C,
        replaceadminmiddlename:result.AdminProfile[0].D,
        updateadminlastname:result.AdminProfile[0].E,
        replaceadminlastname:result.AdminProfile[0].F,
        admingender:result.AdminProfile[0].G,
        adminDOB:result.AdminProfile[0].H,
        updateadminphone:result.AdminProfile[0].I,
        replaceadminphone:result.AdminProfile[0].J,
        Mandatoryleadfirstname:result.Addleadparameters[5].A,
        Mandatoryleademail:result.Addleadparameters[5].B,
        Mandatoryleadphone:result.Addleadparameters[5].C,
        Mandatoryleadgender:result.Addleadparameters[5].D,
        MandatoryleadDOByear:result.Addleadparameters[5].E,
        MandatoryleadDOBmonth:result.Addleadparameters[5].F,
        MandatoryleadDOByearday:result.Addleadparameters[5].G,
        Mandatoryleadconselor:result.Addleadparameters[5].H,
        MandatoryleadCourse:result.Addleadparameters[5].I,
        MandatoryleadAcademy:result.Addleadparameters[5].J,
        MandatoryleadPincode:result.Addleadparameters[5].K,
        Meandatoryleadflatnumber:result.Addleadparameters[5].L,
        Mendatoryleadstreetarea:result.Addleadparameters[5].M,
        firstnameLeadnumbers:result.Addleadparameters[7].A,
        firstnameLeadsymbols:result.Addleadparameters[7].B,
        leademailfieldwithnumbers:result.Addleadparameters[7].C,
        leademailfieldwithsymbols:result.Addleadparameters[7].D,
        leadphonefieldwithletters:result.Addleadparameters[7].E,
        leadphonefieldwithinvalidnum:result.Addleadparameters[7].F,
        leadphonefieldwithvalidnum:result.Addleadparameters[7].G,
        leadphonefieldwithmorethan10digits:result.Addleadparameters[7].H,
        leadphonefieldwithlessthan10digits:result.Addleadparameters[7].I,
        leadphonefieldwithsymbols:result.Addleadparameters[7].J,
        leadpostalcodefieldwithletters:result.Addleadparameters[7].K,
        leadpostalcodefieldwithsymbol:result.Addleadparameters[7].L,
        leadpostalcodefieldlessthan6digit:result.Addleadparameters[7].M,
        leadpostalcodefieldgreaterthan6digit:result.Addleadparameters[7].N,
        leadpostalcodefieldwithvalidpin:result.Addleadparameters[7].O,
        leadflatnumberfieldwithmorethan100letters:result.Addleadparameters[7].P,
        leadareafieldwithgreater100letters:result.Addleadparameters[7].Q,
        leadmiddlenamewithnumbers:result.Addleadparameters[7].R,
        leadmiddlenamewithsymbols:result.Addleadparameters[7].S,
        leadmiddlenamewithvalidname:result.Addleadparameters[7].T,
        leadmiddlenamewithmorethan30characters:result.Addleadparameters[7].U,
        leadlastnamewithnumbers:result.Addleadparameters[7].V,
        leadlastnamewithsymbols:result.Addleadparameters[7].W,
        leadlastnamewithvalidname:result.Addleadparameters[7].X,
        leadlastnamewithgreaterthan30characters:result.Addleadparameters[7].Y,
        leadalternatephonewithletters:result.Addleadparameters[7].Z,
        leadalternatephonewithinvalidnumber:result.Addleadparameters[7].AA,
        leadalternatephonewithvalidnumber:result.Addleadparameters[7].AB,
        leadalternatephonewithgreaterthan10digits:result.Addleadparameters[7].AC,
        leadalternatephonewithlessthan10:result.Addleadparameters[7].AD,
        leadalternatephonewithsymbols:result.Addleadparameters[7].AE,
        leadwhatsappwithletters:result.Addleadparameters[7].AF,
        leadwhatsappwithinvalidnumber:result.Addleadparameters[7].AG,
        leadwhatsappwithvalidnumber:result.Addleadparameters[7].AH,
        leadwhatsappwithgreaterthan10numbers:result.Addleadparameters[7].AI,
        leadwhatsappwithlessthan10:result.Addleadparameters[7].AJ,
        leadwhatsappwithsymbols:result.Addleadparameters[7].AK,
        leadoccupationwithmaxvalidation:result.Addleadparameters[7].AL,
        leadlandmarkfieldwithmaxvalidation:result.Addleadparameters[7].AM,
        prefferedstarttime:result.Addleadparameters[0].V,
        prefferedendtime:result.Addleadparameters[0].W,
        leadprefferedstarttimewithwrongtime:result.Addleadparameters[7].AN,
        leadprefferedcallingendtimewithwrongtime:result.Addleadparameters[7].AO,
        Mandatorystafffirstname:result.AddStaff[4].A,
        Mandatorystaffpersonalphone:result.AddStaff[4].B,
        Mandatorystaffemail:result.AddStaff[4].C,
        Mandatorystaffrole:result.AddStaff[4].D,
        Mandatorystaffdesignation:result.AddStaff[4].E,
        Mandatorystaffdepartment:result.AddStaff[4].F,
        Mandatorystaffteaching:result.AddStaff[4].G,
        Mandatorystaffofficelocation:result.AddStaff[4].H,
        stafffirstnamewithnumbers:result.AddStaff[4].I,
        stafffirstnamewithsymbols:result.AddStaff[4].J,
        stafffirstnamewithmaxvalidation:result.AddStaff[4].K,
        staffmiddlenamewithnumbers:result.AddStaff[4].L,
        staffmiddlenamewithsymbols:result.AddStaff[4].M,
        staffmiddlenamewithvalidname:result.AddStaff[4].N,
        Staffmiddlenamewithmaxvalidation:result.AddStaff[4].O,
        stafflastnamewithnumbers:result.AddStaff[4].P,
        stafflastnamewithsymbols:result.AddStaff[4].Q,
        stafflastnamewithvalidname:result.AddStaff[4].R,
        stafflastnamewithmaxvalidation:result.AddStaff[4].S,
        staffphonewithletters:result.AddStaff[4].T,
        staffphonewithinvalidnumber:result.AddStaff[4].U,
        staffphonewithvalidnumber:result.AddStaff[4].V,
        staffphonewithgreaterthan10:result.AddStaff[4].W,
        staffphonewithlessthan10:result.AddStaff[4].X,
        staffphonewithsymbols:result.AddStaff[4].Y,
        staffworkphonewithletters:result.AddStaff[4].Z,
        staffworkphonewithinvalidnumber:result.AddStaff[4].AA,
        staffworkphonewithvalidnumber:result.AddStaff[4].AB,
        staffworkwithgreaterthan10:result.AddStaff[4].AC,
        staffworkphonewithlessthan10:result.AddStaff[4].AD,
        staffworkphonewithsymbols:result.AddStaff[4].AE,
        staffemailwithnumbers:result.AddStaff[4].AF,
        staffemailwithsymbols:result.AddStaff[4].AG,
        staffemailwithvalidemail:result.AddStaff[4].AH,
        courseoverviewwithmandatorycoursename:result.AddCourse[4].A,
        courseoverviewwithmandatorycourseshrtcode:result.AddCourse[4].B,
        coursenamefieldwithgreaterthan100characters:result.AddCourse[4].C,
        courseshortcodewithgreaterthan100characters:result.AddCourse[4].D,
        coursenamewithvaliddata:result.AddCourse[4].E,
        courseshortcodewithvaliddata:result.AddCourse[4].F,
        Verifycourse:result.AddCourse[4].G,
        coursebasicbycourselocation:result.AddCourse[4].H,
        coursebasicbylangaugeofinsrtuction:result.AddCourse[4].I,
        coursebasicbypracticalrequirement:result.AddCourse[4].J,
        coursebasicbymedicalrequirement:result.AddCourse[4].K,
        coursebasicbymodesofinstruction:result.AddCourse[4].L,
        searchedcoursetobeclicked:result.AddCourse[4].M,
        coursefeeamount:result.AddCourse[4].N,
        coursepaymentredeemablecredit:result.AddCourse[4].O,
        coursepaymentredeemablemasking:result.AddCourse[4].P,
        coursepaymentflatdiscountamountverificationforUpfront:result.AddCourse[4].Q,
        coursepaymentdiscontamountforflat:result.AddCourse[4].R,
        coursepaymentpercentagediscountamountverificationforUpfront:result.AddCourse[4].S,
        coursepaymentdiscontamountforpercentage:result.AddCourse[4].T,
        courseschedulevirtualcapacitybyletters:result.AddCourse[4].U,
        courseschedulevirtualcapacitybysymbols:result.AddCourse[4].V,
        courseschedulephysicalcapacitybyletters:result.AddCourse[4].W,
        courseschedulephysicalcapacitybysymbols:result.AddCourse[4].X,
        courseschedulebatchstarttime:result.AddCourse[4].Y,
        courseschedulebatchendtime:result.AddCourse[4].Z,
        coursepaymentbajajdiscountamountforflat:result.AddCourse[4].AA,
        coursepaymentbajajdiscountamountforpercentage:result.AddCourse[4].AB,
        coursepaymentbajajdownpaymentbypassingmaxvalue:result.AddCourse[4].AC,
        coursepaymentbajajdownpaymentformaskeddata:result.AddCourse[4].AD,
        coursepaymentbajajmaxinstallementswithletters:result.AddCourse[4].AE,
        coursepaymentbajajmaxinstallementswithsymbols:result.AddCourse[4].AF,
        coursepaymentbajajmaxinstallementswithmaxvalue:result.AddCourse[4].AG,
        coursepaymenthdfcdiscountamountforflatdiscount:result.AddCourse[4].AH,
        coursepaymenthdfcdiscountamountforpercentagediscount:result.AddCourse[4].AI,
        coursepaymenthdfcdownpaymentformaxvalue:result.AddCourse[4].AJ,
        coursepaymenthdfcdownpaymentformasked:result.AddCourse[4].AK,
        coursepaymentHDFCmaxinstallmentwithletters:result.AddCourse[4].AL,
        coursepaymentHDFCmaxinstallmentwithsymbols:result.AddCourse[4].AM,
        coursepaymentHDFCmaxinstallmentwithmaxvalue:result.AddCourse[4].AN,
        coursepaymentK11discountamountforflat:result.AddCourse[4].AO,
        coursepaymentK11discountamountforpercentage:result.AddCourse[4].AP,
        coursepaymentK11downpaymentformaxvalue:result.AddCourse[4].AQ,
        coursepaymentK11maxintallmentswithletters:result.AddCourse[4].AS,
        coursepaymentK11maxintallmentswithsymbols:result.AddCourse[4].AT,
        coursepaymentK11maxintallmentswithmaxvalue:result.AddCourse[4].AU,
        coursepaymentpayablediscountamountforflat:result.AddCourse[4].AV,
        coursepaymentpayablediscountamountforpercentage:result.AddCourse[4].AW,
        organizationcode:result.logincred[3].B,
        updateweek2:result.AddCourse[2].AR,
        updateweek3:result.AddCourse[2].AS,
        updateweek4:result.AddCourse[2].AT,
        usernamewithletters:result.logincred[4].B,
        usernamewithsymbols:result.logincred[5].B,
        usernamewithnumbers:result.logincred[6].B,
        usernamewithinvalidemail:result.logincred[7].B,
        usernamewithvalidemail:result.logincred[8].B,
        wrongusername:result.logincred[9].B,
        wrongpassword:result.logincred[10].B,
        forgotpasswordusernamewithletters:result.logincred[11].B,
        forgotpasswordusernamewithsymbols:result.logincred[12].B,
        forgotpasswordusernamewithnumbers:result.logincred[13].B,
        forgotpasswordusernamewithvalidemail:result.logincred[14].B,
        forgotpasswordusernamewithinvalidemail:result.logincred[15].B,
        course1:result.AddCourse[6].A,
        courseshortcode1:result.AddCourse[6].B,
        course2:result.AddCourse[6].C,
        courseshortcode2:result.AddCourse[6].D,
        course3:result.AddCourse[6].E,
        courseshortcode3:result.AddCourse[6].F,
        course4:result.AddCourse[6].G,
        courseshortcode4:result.AddCourse[6].H,
        course5:result.AddCourse[6].I,
        courseshortcode5:result.AddCourse[6].J,
        course6:result.AddCourse[6].K,
        courseshortcode6:result.AddCourse[6].L,

    };
}


module.exports = new dataRequired();